### ISSUE TITLE
Create a gh worfkow for testing gh self hosted runner 

### ISSUE THREAD

**Issue by adrianriobo** [redhat-developer/mapt#256]
This is a following for #211 

Now we have the mechanism in place, we do not want to test it on every PR, as this is an specific feature but it would be great to create a gh workflow to run mapt as self hosted runner and then run some logic on it.

This flow should be triggered manually https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch 

Also this could be used as an example to set the same strategy on other repos

**Comment by anjannath** [comment]
fixed via #282
