### ISSUE TITLE
AKS: add the option for `--enable-app-routing` flag

### ISSUE THREAD

**Issue by zdrapela** [redhat-developer/mapt#288]
For our use for RHDH ([RHIDP-2128](https://issues.redhat.com/browse/RHIDP-2128)), adding an option to enable app routing during the AKS cluster creation would be great. 

The Azure CLI has the flag `--enable-app-routing` 
- e.g. ```az aks create --resource-group <ResourceGroupName> --name <ClusterName> --location <Location> --enable-app-routing --generate-ssh-keys```
- https://learn.microsoft.com/en-us/azure/aks/app-routing#enable-application-routing-using-azure-cli

This would be great addition to https://github.com/redhat-developer/mapt/issues/272

**Comment by adrianriobo** [comment]
Will plan this during next week so this will be in with the next mapt version (featuring the AKS)

**Comment by adrianriobo** [comment]
Unfortunately web application routing can not be set within Pulumi. I opened an issue for it https://github.com/pulumi/pulumi-azure-native/issues/3607

At the moment only the httpApplicationRouting could be added but that one is deprecated in favor of web application routing and will be discontinued on 2025. So I would prefer not to add it here.
