### ISSUE TITLE
[BUG] Documentation is missing information on new parameters to set type of machine based on args 

### ISSUE THREAD

**Issue by adrianriobo** [redhat-developer/mapt#310]
During https://github.com/redhat-developer/mapt/pull/277 a new way to set the type of machine it is required was set based on vm specs as args. 

This is currently working but all the information about those new params and which is the benefit is missing.

**Comment by odockal** [comment]
@adrianriobo Do you think this might get addressed? I am asking @amisskii to start using the 0.7.+ version, but it is hard to find particular tags to use during machine create.

**Comment by adrianriobo** [comment]
What do you mean?
